[package]
name = "iso11783-data"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "ISO 11783 / ISOBUS constant definitions and lookup functions"
keywords = ["j1939", "isobus", "iso11783", "pgn", "ddi"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
default = ["pgn", "isobus_params", "task_controller_ddi"]
pgn = []
isobus_params = []
task_controller_ddi = []

[workspace]
members = ["generator"]
