/// Source: TaskControllerDDI.txt rev 1, downloaded 2026-07-19
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct DdiInfo {
    pub ddi: u16,
    pub name: &'static str,
    /// e.g., "RPM", "degrees Celsius", "kPa" — None if not specified
    pub unit: Option<&'static str>,
    /// Resolution (factor) for physical value conversion: physical = raw * resolution + offset
    pub resolution: f64,
    /// Offset for physical value conversion
    pub offset: f64,
}

pub const DDI_LIST: &[DdiInfo] = &[
    DdiInfo { ddi: 0, name: "Internal Data Base DDI", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 2, name: "Actual Volume Per Area Application Rate as [mm³/m²]", unit: Some("mm³/m²"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 4, name: "Minimum Volume Per Area Application Rate as [mm³/m²]", unit: Some("mm³/m²"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 6, name: "Setpoint Mass Per Area Application Rate", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 8, name: "Default Mass Per Area Application Rate", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 10, name: "Maximum Mass Per Area Application Rate", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 12, name: "Actual Count Per Area Application Rate", unit: Some("/m²"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 14, name: "Minimum Count Per Area Application Rate", unit: Some("/m²"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 16, name: "Setpoint Spacing Application Rate", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 18, name: "Default Spacing Application Rate", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 20, name: "Maximum Spacing Application Rate", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 22, name: "Actual Volume Per Volume Application Rate", unit: Some("mm³/m³"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 24, name: "Minimum Volume Per Volume Application Rate", unit: Some("mm³/m³"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 26, name: "Setpoint Mass Per Mass Application Rate", unit: Some("mg/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 28, name: "Default Mass Per Mass Application Rate", unit: Some("mg/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 30, name: "MaximumMass Per Mass Application Rate", unit: Some("mg/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 32, name: "Actual Volume Per Mass Application Rate", unit: Some("mm³/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 34, name: "Minimum Volume Per Mass Application Rate", unit: Some("mm³/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 36, name: "Setpoint Volume Per Time Application Rate", unit: Some("mm³/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 38, name: "Default Volume Per Time Application Rate", unit: Some("mm³/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 40, name: "Maximum Volume Per Time Application Rate", unit: Some("mm³/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 42, name: "Actual Mass Per Time Application Rate", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 44, name: "Minimum Mass Per Time Application Rate", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 46, name: "Setpoint Count Per Time Application Rate", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 48, name: "Default Count Per Time Application Rate", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 50, name: "Maximum Count Per Time Application Rate", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 52, name: "Actual Tillage Depth", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 54, name: "Minimum Tillage Depth", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 56, name: "Setpoint Seeding Depth", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 58, name: "Default Seeding Depth", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 60, name: "Maximum Seeding Depth", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 62, name: "Actual Working Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 64, name: "Minimum Working Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 66, name: "Setpoint Working Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 68, name: "Default Working Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 70, name: "Maximum Working Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 72, name: "Actual Volume Content", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 74, name: "Setpoint Mass Content", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 76, name: "Maximum Mass Content", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 78, name: "Actual Count Content", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 80, name: "Application Total Volume as [L]", unit: Some("L"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 82, name: "Application Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 84, name: "Mass Per Area Yield", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 86, name: "Volume Per Time Yield", unit: Some("ml/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 88, name: "Count Per Time Yield", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 90, name: "Yield Total Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 92, name: "Volume Per Area Crop Loss", unit: Some("ml/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 94, name: "Count Per Area Crop Loss", unit: Some("/m²"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 96, name: "Mass Per Time Crop Loss", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 98, name: "Percentage Crop Loss", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 100, name: "Crop Contamination", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 102, name: "Actual Bale Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 104, name: "Minimum Bale Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 106, name: "Setpoint Bale Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 108, name: "Default Bale Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 110, name: "Maximum Bale Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 112, name: "Actual Bale Size", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 114, name: "Minimum Bale Size", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 116, name: "Total Area", unit: Some("m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 118, name: "Ineffective Total Distance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 120, name: "Ineffective Total Time", unit: Some("s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 122, name: "Product Density Mass PerCount", unit: Some("mg/1000"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 124, name: "Auxiliary Valve Scaling Extend", unit: Some("%"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 126, name: "Auxiliary Valve Ramp Extend Up", unit: Some("ms"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 128, name: "Auxiliary Valve Ramp Retract Up", unit: Some("ms"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 130, name: "Auxiliary Valve Float Threshold", unit: Some("%"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 132, name: "Auxiliary Valve Progressivity Retract", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 134, name: "Device Element Offset X", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 136, name: "Device Element Offset Z", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 138, name: "Device Mass Capacity (Deprecated)", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 140, name: "Setpoint Percentage Application Rate", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 142, name: "Physical Setpoint Time Latency", unit: Some("ms"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 144, name: "Yaw Angle", unit: Some("°"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 146, name: "Pitch Angle", unit: Some("°"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 148, name: "Total Fuel Consumption", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 150, name: "Instantaneous Fuel Consumption per Area", unit: Some("mm³/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 153, name: "Actual Normalized Difference Vegetative Index (NDVI)", unit: Some("n.a. -"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 155, name: "Physical Object Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 157, name: "Connector Type", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 159, name: "Number of Sub-Units per Section", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 161, name: "Actual Condensed Work State (1-16)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 163, name: "Actual Condensed Work State (33-48)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 165, name: "Actual Condensed Work State (65-80)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 167, name: "Actual Condensed Work State (97-112)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 169, name: "Actual Condensed Work State (129-144)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 171, name: "Actual Condensed Work State (161-176)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 173, name: "Actual Condensed Work State (193-208)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 175, name: "Actual Condensed Work State (225-240)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 177, name: "Actual length of cut", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 179, name: "Actual Cultural Practice", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 181, name: "Dry Mass Per Area Yield", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 183, name: "Yield Total Dry Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 185, name: "Seed Cotton Mass Per Area Yield", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 187, name: "Seed Cotton Mass Per Time Yield", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 189, name: "Yield Total Seed Cotton Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 191, name: "Lint Turnout Percentage", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 193, name: "Setpoint Product Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 195, name: "Minimum Product Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 197, name: "Setpoint Pump Output Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 199, name: "Minimum Pump Output Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 201, name: "Setpoint Tank Agitation Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 203, name: "Minimum Tank Agitation Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 205, name: "SC Setpoint Turn On Time", unit: Some("ms"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 207, name: "Wind speed", unit: Some("mm/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 209, name: "Relative Humidity", unit: Some("%"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 211, name: "Last Bale Flakes per Bale", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 213, name: "Last Bale Average Strokes per Flake", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 215, name: "Lifetime Working Hours", unit: Some("h"), resolution: 0.05, offset: 0.0 },
    DdiInfo { ddi: 217, name: "Last Bale Average Hydraulic Pressure", unit: Some("Pa"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 219, name: "Actual Bale Compression Plunger Load", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 221, name: "Last Bale Applied Preservative", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 223, name: "Last Bale Mass", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 225, name: "Setpoint Working Length", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 227, name: "Minimum Working Length", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 229, name: "Actual Net Weight", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 231, name: "Setpoint Net Weight", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 233, name: "Gross Weight State", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 235, name: "Maximum Gross Weight", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 237, name: "Actual Header Working Height Status", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 239, name: "Yield Hold Status", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 241, name: "Crop Temperature", unit: Some("mK"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 243, name: "Actual Sieve Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 245, name: "Maximum Sieve Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 247, name: "Actual Chaffer Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 249, name: "Maximum Chaffer Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 251, name: "Actual Concave Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 253, name: "Maximum Concave Clearance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 255, name: "Actual Separation Fan Rotational Speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 257, name: "Maximum Separation Fan Rotational Speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 259, name: "Yield Lag Ignore Time", unit: Some("ms"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 261, name: "Average Yield Mass Per Time", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 263, name: "Average Yield Mass Per Area", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 265, name: "Remaining Area", unit: Some("m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 267, name: "Lifetime Application Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 269, name: "Lifetime Yield Total Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 271, name: "Lifetime Total Area", unit: Some("m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 273, name: "Lifetime Ineffective Total Distance", unit: Some("m"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 275, name: "Lifetime Ineffective Total Time", unit: Some("s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 277, name: "Lifetime Average Fuel Consumption per Time", unit: Some("mm³/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 279, name: "Lifetime Yield Total Dry Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 281, name: "Lifetime Yield Total Lint Cotton Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 283, name: "Precut Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 285, name: "Lifetime Precut Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 287, name: "Setpoint Prescription Mode", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 289, name: "Setpoint Work State", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 291, name: "Setpoint Condensed Work State (17-32)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 293, name: "Setpoint Condensed Work State (49-64)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 295, name: "Setpoint Condensed Work State (81-96)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 297, name: "Setpoint Condensed Work State (113-128)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 299, name: "Setpoint Condensed Work State (145-160)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 301, name: "Setpoint Condensed Work State (177-192)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 303, name: "Setpoint Condensed Work State (209-224)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 305, name: "Setpoint Condensed Work State (241-256)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 307, name: "True Rotation Point Y-Offset", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 309, name: "Minimum Percentage Application Rate", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 311, name: "Relative Yield Potential", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 313, name: "Maximum Relative Yield Potential", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 315, name: "Average Percentage Crop Dry Matter", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 317, name: "Ineffective Total Fuel Consumption", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 319, name: "Ineffective Total Diesel Exhaust Fluid Consumption", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 321, name: "Last unloaded Weight", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 323, name: "Unload Identification Number", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 325, name: "Lifetime Application Total Volume", unit: Some("L"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 327, name: "Actual Header Speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 329, name: "Maximum Header Speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 331, name: "Actual Cutting drum speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 333, name: "Maximum Cutting drum speed", unit: Some("/s"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 335, name: "Front PTO hours", unit: Some("s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 337, name: "Lifetime Front PTO hours", unit: Some("h"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 339, name: "Total Loading Time", unit: Some("s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 341, name: "Setpoint Grain Kernel Cracker Gap", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 343, name: "Minimum Grain Kernel Cracker Gap", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 345, name: "Setpoint Swathing Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 347, name: "Minimum Swathing Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 349, name: "Nozzle Drift Reduction", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 351, name: "Application Total Volume in [ml]", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 353, name: "Total Application of Nitrogen [N2]", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 355, name: "Total Application of Phosphor", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 357, name: "Total Application of Dry Matter", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 359, name: "Average Dry Yield Mass Per Area", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 361, name: "Last Bale Density", unit: Some("mg/l"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 363, name: "Last Bale Dry Mass", unit: Some("g"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 365, name: "Setpoint Downforce Pressure", unit: Some("Pa"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 367, name: "Condensed Section Override State (1-16)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 369, name: "Condensed Section Override State (33-48)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 371, name: "Condensed Section Override State (65-80)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 373, name: "Condensed Section Override State (97-112)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 375, name: "Condensed Section Override State (129-144)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 377, name: "Condensed Section Override State (161-176)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 379, name: "Condensed Section Override State (193-208)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 381, name: "Condensed Section Override State (225-240)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 383, name: "Apparent Wind Direction", unit: Some("°"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 385, name: "MSL Atmospheric Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 387, name: "Total Revolutions in Fractional Revolutions", unit: Some("#"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 389, name: "Setpoint Revolutions specified as count per time", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 391, name: "Default Revolutions Per Time", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 393, name: "Maximum Revolutions Per Time", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 395, name: "Actual Diesel Exhaust Fluid Tank Content", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 397, name: "Actual Speed", unit: Some("mm/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 399, name: "Maximum Speed", unit: Some("mm/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 401, name: "Actual Application of Nitrogen [N2] as [mg/l]", unit: Some("mg/l"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 403, name: "Actual application of Phosphor", unit: Some("mg/l"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 405, name: "Actual application of Dry Matter", unit: Some("mg/l"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 407, name: "Average Crude Protein Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 409, name: "Total Diesel Exhaust Fluid Consumption", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 411, name: "Instantaneous Diesel Exhaust Fluid Consumption per Area", unit: Some("mm³/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 413, name: "Lifetime Average Diesel Exhaust Fluid Consumption per Time", unit: Some("mm³/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 415, name: "Actual Seed Singulation Percentage", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 417, name: "Actual Seed Skip Percentage", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 419, name: "Actual Seed Multiple Percentage", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 421, name: "Actual Seed Spacing Deviation", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 423, name: "Actual Coefficient of Variation of Seed Spacing Percentage", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 425, name: "Setpoint Maximum Allowed Seed Spacing Deviation", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 427, name: "Actual Downforce as Force", unit: Some("N"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 429, name: "Unloaded Total Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 431, name: "Lifetime Unloaded Total Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 433, name: "Actual  Application Rate of Nitrogen [N2]", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 435, name: "Maximum  Application Rate of Nitrogen [N2]", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 437, name: "Actual  Application Rate of Ammonium", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 439, name: "Maximum  Application Rate of Ammonium", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 441, name: "Actual  Application Rate of Phosphor", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 443, name: "Maximum  Application Rate of Phosphor", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 445, name: "Actual  Application Rate of Potassium", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 447, name: "Maximum Application Rate of Potassium", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 449, name: "Actual  Application Rate of Dry Matter", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 451, name: "Maximum Application Rate of Dry Matter", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 453, name: "Unloaded Total Volume", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 455, name: "Lifetime Unloaded Total Volume", unit: Some("L"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 457, name: "Last unloaded Volume", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 459, name: "Unloaded Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 461, name: "Lifetime Unloaded Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 463, name: "Last unloaded Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 465, name: "Lifetime Haul Counter", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 467, name: "Actual Percentage Content", unit: Some("%"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 469, name: "Estimated Soil Water Condtion", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 471, name: "Setpoint Cultural Practice", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 473, name: "Minimum length of cut", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 475, name: "Setpoint Bale Hydraulic Pressure", unit: Some("Pa"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 477, name: "Maximum Bale Hydraulic Pressure", unit: Some("Pa"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 479, name: "Minimum Flake Size", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 481, name: "Setpoint Number of Subbales", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 483, name: "Setpoint Engine Speed", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 485, name: "Minimum Engine Speed", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 488, name: "Diesel Exhaust Fluid Tank Percentage Level", unit: Some("%"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 490, name: "Maximum Fuel Tank Content", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 492, name: "Total Engine Hours", unit: Some("h"), resolution: 0.05, offset: 0.0 },
    DdiInfo { ddi: 494, name: "Last Event Partner ID (Byte 1-4)", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 496, name: "Last Event Partner ID (Byte 9-12)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 498, name: "Last Event Partner ID Type", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 500, name: "Last Event Partner ID Device Class", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 502, name: "Actual Engine Torque", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 504, name: "Maximum Engine Torque", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 506, name: "Setpoint Track Control Level", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 508, name: "Unique Guidance Reference Line ID", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 510, name: "Guidance Track Number to the right", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 512, name: "Guidance Line Swath Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 514, name: "GNSS Quality", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 516, name: "Tramline Overdosing Rate", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 518, name: "Actual Tramline Condensed Work State (1-16)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 520, name: "Actual Canopy Height", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 522, name: "Twine Bale Total Count (Deprecated)", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 524, name: "Lifetime Twine Bale Total Count (Deprecated)", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 526, name: "Actual Cooling Fluid Temperature", unit: Some("mK"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 529, name: "Setpoint Tillage Disc Gang Angle", unit: Some("°"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 531, name: "Actual Applied Preservative Per Yield Mass", unit: Some("mm³/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 533, name: "Default Applied Preservative Per Yield Mass", unit: Some("mm³/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 535, name: "Maximum Applied Preservative Per Yield Mass", unit: Some("mm³/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 537, name: "Lifetime Applied Preservative", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 539, name: "Actual Preservative Tank Volume", unit: Some("ml"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 541, name: "Actual PTO Speed", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 543, name: "Default PTO Speed", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 545, name: "Maximum PTO Speed", unit: Some("r/min"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 547, name: "Setpoint Bale Compression Plunger Load (N)", unit: Some("N"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 549, name: "Last Bale Average Bale Compression Plunger Load (N)", unit: Some("N"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 551, name: "Actual PTO Torque", unit: Some("N*m"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 553, name: "Default PTO Torque", unit: Some("N*m"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 555, name: "Maximum PTO Torque", unit: Some("N*m"), resolution: 0.0001, offset: 0.0 },
    DdiInfo { ddi: 557, name: "Setpoint Electrical Current", unit: Some("A"), resolution: 0.005, offset: 0.0 },
    DdiInfo { ddi: 559, name: "Minimum Electrical Current", unit: Some("A"), resolution: 0.005, offset: 0.0 },
    DdiInfo { ddi: 561, name: "Default Electrical Current", unit: Some("A"), resolution: 0.005, offset: 0.0 },
    DdiInfo { ddi: 563, name: "Default Voltage", unit: Some("V"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 565, name: "Minimum Voltage", unit: Some("V"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 567, name: "Actual Electrical Resistance", unit: Some("Ohm"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 569, name: "Actual Electrical Power", unit: Some("W"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 571, name: "Maximum Electrical Power", unit: Some("W"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 573, name: "Total Electrical Energy", unit: Some("kWh"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 575, name: "Actual  Electrical Energy per Area Application Rate", unit: Some("kWh/m²"), resolution: 0.0000001, offset: 0.0 },
    DdiInfo { ddi: 577, name: "Minimum  Electrical Energy per Area Application Rate", unit: Some("kWh/m²"), resolution: 0.0000001, offset: 0.0 },
    DdiInfo { ddi: 579, name: "Actual Temperature", unit: Some("mK"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 581, name: "Maximum Temperature", unit: Some("mK"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 583, name: "Setpoint Frequency", unit: Some("Hz"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 585, name: "Minimum Frequency", unit: Some("Hz"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 587, name: "Previous Rainfall", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 589, name: "Actual Volume Per Area Application Rate as [ml/m²]", unit: Some("ml/m²"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 591, name: "Maximum Volume Per Area Application Rate as [ml/m²]", unit: Some("ml/m²"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 593, name: "Traction Type", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 595, name: "Machine Mode", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 597, name: "Total Distance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 599, name: "Total Distance Field", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 601, name: "Total Distance Street", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 603, name: "Actual Tramline Condensed Work State (17-32)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 605, name: "Actual Tramline Condensed Work State (49-64)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 607, name: "Actual Tramline Condensed Work State (81-96)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 609, name: "Actual Tramline Condensed Work State (113-128)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 611, name: "Actual Tramline Condensed Work State (145-160)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 613, name: "Actual Tramline Condensed Work State (177-192)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 615, name: "Actual Tramline Condensed Work State (209-224)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 617, name: "Actual Tramline Condensed Work State (241-256)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 619, name: "Setpoint Tramline Condensed Work State (33-48)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 621, name: "Setpoint Tramline Condensed Work State (65-80)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 623, name: "Setpoint Tramline Condensed Work State (97-112)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 625, name: "Setpoint Tramline Condensed Work State (129-144)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 627, name: "Setpoint Tramline Condensed Work State (161-176)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 629, name: "Setpoint Tramline Condensed Work State (193-208)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 631, name: "Setpoint Tramline Condensed Work State (225-240)", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 633, name: "Setpoint Volume per distance Application Rate", unit: Some("ml/m"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 635, name: "Default Volume per distance Application Rate", unit: Some("ml/m"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 637, name: "Maximum Volume per distance Application Rate", unit: Some("ml/m"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 639, name: "Actual Tire Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 641, name: "Minimum Tire Pressure", unit: Some("Pa"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 643, name: "Actual Tire Temperature", unit: Some("mK"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 645, name: "Last Bale Number of Knives", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 647, name: "Last Bale Binding Mesh Consumption", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 649, name: "Last Bale Binding Film Stretching", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 651, name: "Last Bale Wrapping Film Consumption", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 653, name: "Last Bale Wrapping Film Overlap Percentage", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 655, name: "Electrical Apparent Soil Conductivity", unit: Some("mS/m"), resolution: 0.1, offset: 0.0 },
    DdiInfo { ddi: 657, name: "SC Actual Turn Off Time", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 659, name: "Actual CO2 equivalent specified as mass per time", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 661, name: "Actual CO2 equivalent specified as mass per yield", unit: Some("mg/kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 663, name: "Actual CO2 equivalent specified as mass per count", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 665, name: "Lifetime total CO2 equivalent", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 667, name: "Distance between Guidance Track Number 0R and 1", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 669, name: "Track Number Shift", unit: Some("not defined"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 671, name: "Primary Tire Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 673, name: "Secondary Working Width", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 675, name: "Secondary Wheel Distance", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 677, name: "Last Bale Binding Film Layers", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 679, name: "Crop Contamination Total Mass", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 681, name: "Film bale Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 683, name: "Twine bale Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 685, name: "Lifetime Film Bale Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 687, name: "Lifetime Twine Bale Total Count", unit: Some("#"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 689, name: "Effective Total Electrical Battery Energy Consumption", unit: Some("kWh"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 691, name: "Instantaneous Electrical Battery Energy Consumption per Time", unit: Some("W"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 693, name: "Lifetime Total Loading Time", unit: Some("s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 695, name: "Mesh Total Used", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 697, name: "Twine Total Used", unit: Some("mm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 699, name: "Average Mass Per Load", unit: Some("kg"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 701, name: "Actual Starch Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 703, name: "Actual Ash Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 705, name: "Actual Sugar Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 707, name: "Actual Lipids Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 709, name: "Actual Crude Fat Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 711, name: "Actual Crude Fiber Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 713, name: "Actual Nitrogen (TKN) Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 715, name: "Actual Phosphates Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 717, name: "Actual Potassium Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 719, name: "Actual ADL Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 721, name: "Actual ADF Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 723, name: "Actual NDF Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 725, name: "Actual uNDFom240 Content", unit: Some("ppm"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 727, name: "Actual Biomethanation Production Potential", unit: Some("mm³/kg"), resolution: 0.000001, offset: 0.0 },
    DdiInfo { ddi: 729, name: "Average Corn Silage Processing Score", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 32768, name: "Maximum Droplet Size", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 32770, name: "Maximum Crop Grade Length", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 32772, name: "Maximum Crop Contamination Mass per Time", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 32774, name: "Maximum Corn Silage Processing Score", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 36865, name: "Minimum Crop Grade Diameter", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 36867, name: "Minimum Crop Contamination Mass per Area", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 36869, name: "Minimum Crop Conditioning Intensity", unit: Some("%"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 40960, name: "Default Droplet Size", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 40962, name: "Default Crop Grade Length", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 40964, name: "Default Crop Contamination Mass per Time", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 45056, name: "Actual Droplet Size", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 45058, name: "Actual Crop Grade Length", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 45060, name: "Actual Crop Contamination Mass per Time", unit: Some("mg/s"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 45062, name: "Actual Corn Silage Processing Score", unit: Some("%"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 49153, name: "Setpoint Crop Grade Diameter", unit: Some("mm"), resolution: 0.001, offset: 0.0 },
    DdiInfo { ddi: 49155, name: "Setpoint Crop Contamination Mass per Area", unit: Some("mg/m²"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 49157, name: "Setpoint Crop Conditioning Intensity", unit: Some("%"), resolution: 0.01, offset: 0.0 },
    DdiInfo { ddi: 57342, name: "PGN Based Data", unit: Some("n.a. -"), resolution: 1.0, offset: 0.0 },
    DdiInfo { ddi: 57344, name: "65534 Proprietary DDI Range", unit: Some("n.a. -"), resolution: 0.0, offset: 0.0 },
];

/// Lookup DDI info by DDI value.
pub fn lookup(ddi: u16) -> Option<&'static DdiInfo> {
    match DDI_LIST.binary_search_by_key(&ddi, |info| info.ddi) {
        Ok(idx) => Some(&DDI_LIST[idx]),
        Err(_) => None,
    }
}

/// Convert raw i32 value to physical value using the DDI's resolution and offset.
pub fn to_physical(ddi: u16, raw: i32) -> Option<f64> {
    let info = lookup(ddi)?;
    Some((raw as f64) * info.resolution + info.offset)
}
